apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ventas
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  rules:
  - host: ventas.kazer.es
    http:
      paths:
      - path: /
        backend:
          serviceName: ventas
          servicePort: 80
  tls:
  - secretName: ventas-tls-cert
    hosts:
    - ventas.kazer.es